# industrial-flow sample configuration

sites:
  - id: site1
    enabled: true
    pi:
      provider: simulator
      server: PI-SERVER-01
      pi_timezone: America/Sao_Paulo
      username:
      password:
    tags_file: config/tags.txt
read:
  interval_seconds: 60
  window_seconds: 300
  tag_partition_size: 250
  max_workers: 8
  batch_size: 10000
  queue_max_size: 50
  max_publish_retries: 3
  retry_sleep_seconds: 2.0

# Caminhos de cache de metadados locais
cache:
  point_cache_file: .cache/industrial-flow-pointids.json
  digital_state_cache_file: .cache/industrial-flow-digital-states.json
writer:
  type: console
  pubsub:
    project_id: my-industrial-flow-project
    subscription_id: industrial-flow-writer-sub
    service_account_file: config/gcp-service-account.json
realtime:
  type: console
  read:
    interval_seconds: 60
    window_seconds: 120
    tag_partition_size: 250
    max_workers: 8
    batch_size: 1000
    max_publish_retries: 3
    retry_sleep_seconds: 2
  file:
    output_path: output/events.json
  kafka:
    bootstrap_servers: localhost:9092
    topic: industrial-flow.pi-tags
  bigquery:
    project_id: my-industrial-flow-project
    dataset: industrial
    table: pi_data
    service_account_file: config/gcp-service-account.json
historical:
  type: parquet
  read:
    interval_seconds: 60
    window_seconds: 172800
    tag_partition_size: 250
    max_workers: 8
    batch_size: 10000
  parquet:
    output_dir: output/parquet
  gcs:
    bucket: my-industrial-flow-bucket
    delete_local_file_after_upload: true
    service_account_file: config/gcp-service-account.json
  bigquery:
    project_id: my-industrial-flow-project
    dataset: industrial
    table: pi_data
    service_account_file: config/gcp-service-account.json
